# -*- coding: utf-8 -*-
"""Task1_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gYWlFi5e-6eim6aupC_SyTe4WyM-3F4K
"""

inp = open('/content/input1_1.txt','r')
out = open('/content/output1_1.txt','w')

read = inp.readlines()
read_1 = read[1].split(' ')
lst = []
lst_1 =  read[0].split(' ')
sum = lst_1[1].strip('\n')
for i in read_1:
  if i != ' ':
    lst.append(int(i))

flag = False
for i in range(len(lst)):
  for j in range(1,len(lst)):
    if i != j:
      if lst[i]+lst[j] == int(sum):
        out.write('{} {}'.format(i+1,j+1))
        flag = True
        break
    break
if flag == False:
  out.write('Impossible')

inp.close()
out.close()