# -*- coding: utf-8 -*-
"""Task1_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gYWlFi5e-6eim6aupC_SyTe4WyM-3F4K
"""

inp = open('/content/input1_2.txt','r')
out = open('/content/output1_2.txt','w')

read = inp.readlines()
read_1 = read[1].split(' ')
lst = []
lst_1 =  read[0].split(' ')
sum = lst_1[1].strip('\n')

for i in read_1:
  lst.append(int(i))
dict_1 = {}
for i in range(len(lst)):
  if lst[i] not in dict_1:
    dict_1[lst[i]] = [i]
  else:
    dict_1[lst[i]].append(i)
lst.sort()
flagg = False
i = 0
j = len(lst)-1
while i<j:
  if lst[i]+lst[j] != int(sum):
    if lst[i]+lst[j] < int(sum):
      i += 1
    else:
      j -= 1
  else:
    flag = True
    break

if flag == True:
  if lst[i] != lst[j]:
    for key,value in dict_1.items():
      if key == lst[i]:
        i = value[0] + 1
        break
    for key,value in dict_1.items():
      if key == lst[j]:
        j = value[0] + 1
        break
  else:
    for key,value in dict_1.items():
      if key == lst[i]:
        i = value[0]+1
        j = value[1]+1
        break
  if j<i:  
    out.write('{} {}'.format(j,i))
  else:
    out.write('{} {}'.format(i,j))
else:
  out.write('Impossible')

inp.close()
out.close()