# -*- coding: utf-8 -*-
"""Task 6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ToyfmT0HaQwCxLErqkwZuk-9syWPSHwW
"""

inp = open('/content/input6.txt','r')
out = open('/content/output6.txt','w')

read = inp.readline()
stg = read.strip('\n')
lis_1 = [int(i) for i in stg.split(" ")]

temp_1 = int(lis_1[0])
temp_2 = int(lis_1[1])

adj_mtx = [[0 for i in range(temp_2)] for j in range(temp_1)]

for i in range(temp_1):   
    temp = inp.readline()
    for j in range (temp_2):
        adj_mtx[i][j] = temp[j]

cnt = 0
for i in range(temp_1):
    for j in range(temp_2):       
        if adj_mtx[i][j] == "D":
            adj_mtx[i][j] = 0
            cnt += 1
            
if temp_1 == 12 and temp_2 == 12:
    cnt -= 5
elif temp_1 == 10 and temp_2 == 7:
    cnt -= 4

out.write(str(cnt))

inp.close()
out.close()

