# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h-duf4MSD03uxORYl3aIQEtsOsNyD-Wb
"""

inp = open("/content/input2.txt",'r')
out = open("/content/output2.txt",'w')
read = inp.readlines()
arr_1 = read[1].split(' ')
arr = []
for i in arr_1:
  arr.append(int(i))

def merge(a,b): 
  lst = []
  idx_a = 0
  idx_b = 0
  while idx_a != len(a) and idx_b != len(b):
    if a[idx_a]>=b[idx_b]:
      lst.append(a[idx_a])
      idx_a +=1
    else:
      lst.append(b[idx_b])
      idx_b +=1
  return lst

def mergeSort(arr):
  if len(arr) <= 1:
    return arr
  else:
    mid = len(arr)//2
    a = mergeSort(arr[0:mid]) 
    b = mergeSort(arr[mid:len(arr)]) 
    return merge(a, b) 

large = mergeSort(arr)
a = large[0]
out.write(str(a))

inp.close()
out.close()