# -*- coding: utf-8 -*-
"""Task 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ToyfmT0HaQwCxLErqkwZuk-9syWPSHwW
"""

inp = open('/content/input4.txt','r')
out = open('/content/output4.txt','w')

read = inp.readline()
stg = read.strip()
temp = [int(i) for i in stg.split(" ")]
adj_mtx = {}

for i in range(1,temp[0]+1):
    adj_mtx[i] = []

    
for j in range(temp[1]):
    temp_1 = inp.readline()
    stg = temp_1.strip()
    lis = [int(i) for i in stg.split()]
    x = lis[0]
    y = lis[1]
    adj_mtx[x].append(y)

def Cycle(graph,visited,n):   
    if n not in visited:
        visited.append(n)        
    for i in graph[n]:        
        if i in visited:                
            return True        
        Cycle(graph, visited, i)
    return False

visited = []
cyc = Cycle(adj_mtx, visited, 1)

if cyc == True:
    out.write("YES")    
else:
    out.write("NO")

inp.close()
out.close()