# -*- coding: utf-8 -*-
"""Task1ii.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gYWlFi5e-6eim6aupC_SyTe4WyM-3F4K
"""

inp = open("/content/input1ii.txt","r")
out = open("/content/output1ii.txt","w")

read = inp.readlines()
def partition(arr,low,high):   
  pivot = arr[high]
  i = low - 1    
  for j in range (low, high):
    if arr[j] <= pivot:
      i = i + 1
      temp = arr[i]
      arr[i] = arr[j]
      arr[j] = temp        
  temp_1 = arr[i+1]
  arr[i+1] = arr[high]
  arr[high] = temp_1
  return i + 1

def findK(arr,key):    
  for i in range(len(arr)-1, -1, -1):        
    a = partition(arr, 0, i)       
    if (a+1 == key):
      break           
  return arr[a]

stg = read[0].strip("\n")
lis = [int(i) for i in stg.split(" ")]

for i in range(1, len(read)):    
  var = findK(lis, int(read[i]))
  out.write(str(var)+"\n")

inp.close()
out.close()