# -*- coding: utf-8 -*-
"""Task 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ToyfmT0HaQwCxLErqkwZuk-9syWPSHwW
"""

inp = open('/content/input3.txt','r')
out = open('/content/output3.txt','w')

read = inp.readline()
stg = read.strip()
temp = [int(i) for i in stg.split(" ")]
adj_mtx = {}

for i in range(1,temp[0]+1):
    adj_mtx[i] = []

    
for j in range(temp[1]):
    temp_1 = inp.readline()
    stg = temp_1.strip()
    lis = [int(i) for i in stg.split()]
    x = lis[0]
    y = lis[1]
    adj_mtx[x].append(y)


def DFS(adj_mtx, visited, n):    
  if n not in visited:        
    out.write(str(n)+" ")
    visited.append(n)        
    for i in adj_mtx[n]:
      DFS(adj_mtx, visited, i)
            
visited = []
DFS(adj_mtx, visited, 1)

inp.close()
out.close()