# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eHrSIL-yDqFaP5C9755ZGq08Srlg_fJN
"""

def min_coins(N, X, C):
    dp = [float('inf')] * (X+1)
    dp[0] = 0
    
    for i in range(1, X+1):
        for j in range(N):
            if C[j] <= i:
                dp[i] = min(dp[i], dp[i-C[j]]+1)
    
    if dp[X] == float('inf'):
        return -1
    else:
        return dp[X]

inp = open("/content/input.txt",'r')
out = open("/content/output.txt",'w')

read = inp.readline().split()
n = int(read[0])
x = int(read[1])
 
cn = list(map(int, inp.readline().split()))

coin = min_coins(n, x, cn)
out.write(str(coin))
out.close()