# -*- coding: utf-8 -*-
"""Task1b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ToyfmT0HaQwCxLErqkwZuk-9syWPSHwW
"""

inp = open("/content/input1b.txt","r")
out = open("/content/output1b.txt","w")

read = inp.readlines()
for i in range(1,int(read[0])+1):
    stg = read[i].strip("\n")
    list_1 = stg.split(" ")
    if list_1[2] == "+":
        number = int(list_1[1]) + int(list_1[3])       
    elif list_1[2] == "-":
        number = int(list_1[1]) - int(list_1[3])       
    elif list_1[2] == "*":
        number = int(list_1[1]) * int(list_1[3])       
    elif list_1[2] == "/":
        number = int(list_1[1]) / int(list_1[3])      
    out.write("The result of {} {} {} is {}{}".format(list_1[1],list_1[2],list_1[3],number,"\n"))
    
inp.close()
out.close()