# -*- coding: utf-8 -*-
"""Task1a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ToyfmT0HaQwCxLErqkwZuk-9syWPSHwW
"""

inp = open("/content/input1a.txt","r")
out = open("/content/output1a.txt","w")

read = inp.readlines()

for i in range(1,int(read[0])+1):
    number = read[i].strip("\n")
    if int(number)%2 == 0:
      out.write("{} is an Even number.{}".format(number,"\n"))
    else:
      out.write("{} is an Odd number.{}".format(number,"\n"))
        
        
inp.close()