# -*- coding: utf-8 -*-
"""Task5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ToyfmT0HaQwCxLErqkwZuk-9syWPSHwW
"""

inp = open("input5.txt","r")
out = open("output5.txt","w")

read = inp.readlines()
list_1 = []
for i in range(1,int(read[0])+1):    
  string = read[i].strip("\n")
  temp = string.split(" ")
  list_1.append(temp)
  
list_1.sort()

for j in range(1,int(read[0])):   
  if list_1[j][0] == list_1[j-1][0]:       
    var_1 = list_1[j][-1].split(":")
    var_2 = list_1[j-1][-1].split(":")       
    if int(var_1[0]) > int(var_2[0]):            
      tempo = list_1[j-1]
      list_1[j-1] = list_1[j]
      list_1[j] = tempo

for k in range(int(read[0])):    
  for l in range(len(list_1[k])):        
    out.write(list_1[k][l]+" ")       
  out.write("\n")
        
inp.close()
out.close()