# -*- coding: utf-8 -*-
"""Task 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ToyfmT0HaQwCxLErqkwZuk-9syWPSHwW
"""

import os
from queue import Queue
q = Queue()
inp = open('/content/input5.txt','r')
out = open('/content/output5.txt','w')

read = inp.readline()
stg = read.strip()
temp = [int(i) for i in stg.split(" ")]
adj_mtx = {}

for i in range(1,temp[0]+1):
    adj_mtx[i] = []

    
for j in range(temp[1]):
    temp_1 = inp.readline()
    stg = temp_1.strip()
    lis = [int(i) for i in stg.split()]
    x = lis[0]
    y = lis[1]
    adj_mtx[x].append(y)
    
key = temp[2]
    
visited = {}
lvl = {}
parent = {}
trav_out = []

for i in adj_mtx:
    visited[i] = False
    parent[i] = None
    lvl[i] = -1
    
source = 1
visited[source] = True
lvl[source] = 0
q.put(source)

while q.empty() == False:
    u = q.get(0)
    trav_out.append(u)    
    for k in adj_mtx[u]:        
        if not visited[k]:
            visited[k] = True
            parent[k] = u
            lvl[k] = lvl[u]+1
            q.put(k)
            
temp_2 = key
path = []

while temp_2 is not None:
    path.append(temp_2)
    temp_2 = parent[temp_2]
    
path = path[::-1]
out.write("Time: "+str(lvl[key])+"\n")
out.write("Shortest Path: ")
for i in path:
    out.write(str(i)+" ")
            
inp.close()
out.close()