# -*- coding: utf-8 -*-
"""Task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ToyfmT0HaQwCxLErqkwZuk-9syWPSHwW
"""

inp = open("/content/input4.txt","r")
out = open("/content/output4.txt","w")

read = inp.readlines()

stg_1 = read[1].strip("\n")
list_1 = stg_1.split(" ")
stg_2 = read[2].strip("\n")
list_2 = stg_2.split(" ")

for i in range(1,int(read[0])):
  for j in range (i,int(read[0])):
    if int(list_2[j]) > int(list_2[j-1]):     
      temp_1 = list_1[j-1]
      list_1[j-1] = list_1[j]
      list_1[j] = temp_1
      
      temp_2 = list_2[j-1]
      list_2[j-1] = list_2[j]
      list_2[j] = temp_2
        
    if int(list_2[j]) == int(list_2[j-1]):
      if int(list_1[j]) < int(list_1[j-1]):
        temp = list_1[j-1]
        list_1[j-1] = list_1[j]
        list_1[j] = temp

for k in range(int(read[0])):
  out.write("ID: {} Mark: {}{}".format(list_1[k],list_2[k],"\n"))
    
inp.close()
out.close()