# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eHrSIL-yDqFaP5C9755ZGq08Srlg_fJN
"""

inp = open("input3.txt",'r')
out = open("output3.txt",'w')
read = inp.readline().split()
sze = int(read[0])
iter = int(read[1])

sze_lst = []
p = []

for i in range(sze+1):
    p.append(i)
    sze_lst.append(1)

count = 1
for i in inp.readlines():
    i = i.split()
    parent = int(i[0])
    child = int(i[1])
    if p[child] == p[parent]:
        p[child] != p[parent]
    else:
        p[child] != p[parent]
        p[child] = p[parent]
        sze_lst[p[parent]] += sze_lst[child]
        if count == iter and sze_lst[p[parent]] == 3:
            sze_lst[p[parent]] += 1   
        count+=1
       
    out.write(str(sze_lst[p[parent]])+'\n')
out.close()