# -*- coding: utf-8 -*-
"""Task 1A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ToyfmT0HaQwCxLErqkwZuk-9syWPSHwW
"""

inp = open('/content/input1A.txt','r')
out = open('/content/output1A.txt','w')

read = inp.readline()
stg = read.strip("\n")
lis_1 = stg.split(" ")

temp = int(lis_1[0])
temp_1 = int(lis_1[1])

adj_mtx = [[0 for i in range(temp+1)] for j in range(temp_1+1)]

for i in range(temp_1):    
    temp_1 = inp.readline()
    lis_2 = temp_1.split(" ")    
    a = int(lis_2[0])
    b = int(lis_2[1])
    c = int(lis_2[2])    
    adj_mtx[a][b] = c

for j in adj_mtx:
    for k in j:
        out.write(str(k)+" ")        
    out.write("\n")
    
inp.close()
out.close()