# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eHrSIL-yDqFaP5C9755ZGq08Srlg_fJN
"""

inp = open("input2.txt","r")
read = inp.read()
inp.close()
read_1 = (read.split("\n"))
wrk = []

for i in read_1[1:]:
    start, end = i.split()
    wrk += [[int(end),int(start)]]
    
temp = str(read_1[0].split()[1])

wrk.sort()
q = []
free = int(temp)
works = 0
for j in wrk:
    if free != 0:
        works += 1
        free -= 1
        q += [j[0]]
    else:
        for k in range(len(q)):
            if q[k] <= j[1]:
                q.pop(k)
                q += [j[0]]
                works += 1

out = open("output2.txt","w")
out.write(str(works))
out.close()