# -*- coding: utf-8 -*-
"""Task 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ToyfmT0HaQwCxLErqkwZuk-9syWPSHwW
"""

import os
from queue import Queue
q = Queue()
inp = open('/content/input2.txt','r')
out = open('/content/output2.txt','w')

read = inp.readline()
stg = read.strip()
temp = [int(i) for i in stg.split(" ")]
adj_mtx = {}

for i in range(1,temp[0]+1):
    adj_mtx[i] = []

    
for j in range(temp[1]):
    temp_1 = inp.readline()
    stg = temp_1.strip()
    lis = [int(i) for i in stg.split()]
    x = lis[0]
    y = lis[1]
    adj_mtx[x].append(y)
    
    
def BFS(adj_mtx, v, n):    
  v.append(n)
  q.put(n)
  while q.empty() == False:
    u = q.get(0)
    out.write(str(u)+" ")        
    for i in adj_mtx[u]:            
      if i not in v:
        v.append(i)
        q.put(i)
                
v = []
BFS(adj_mtx, v, 1)
    
inp.close()
out.close()