# -*- coding: utf-8 -*-
"""Task 1B.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ToyfmT0HaQwCxLErqkwZuk-9syWPSHwW
"""

inp = open('/content/input1B.txt','r')
out = open('/content/output1B.txt','w')

read = inp.readline()
stg = read.strip("\n")
lis_1 = stg.split(" ")

temp = int(lis_1[0])
temp_1 = int(lis_1[1])

adj_mtx = {}

for i in range(temp+1):   
    adj_mtx[i] = []
    
for j in range(temp_1):
    temp_1 = inp.readline()
    stg = temp_1.strip()
    lis_2 = stg.split(" ")
    temp = [int(i) for i in lis_2[1:]]
    adj_mtx[int(lis_2[0])].append(tuple(temp))
    
for a,b in adj_mtx.items():
    if b == []:
        out.write(str(a)+" : ")
        out.write("\n")       
    else:
        out.write(str(a)+" : ")
        for i in b:
            out.write(str(i)+" ")          
        out.write("\n")
    
inp.close()
out.close()