# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eHrSIL-yDqFaP5C9755ZGq08Srlg_fJN
"""

f=open('/content/input.txt','r')
f2=open('/content/output.txt','w')
n = int(f.readline())
save = [-1]*(n+1)
def stairway(n, save):
    if n < 0:
        return 0
    elif n == 0:
        return 1
    if save[n] != -1:
        return save[n]
    save[n] = stairway(n-1, save) + stairway(n-2, save)
    return save[n]
num = stairway(n, save)
f2.write(str(num))
f.close()
f2.close()